# Output the infrastructure configuration to console
output "infra_config" {
  description = "Infrastructure configuration for Datafold deployment"
  value = templatefile(
    "${path.module}/../templates/infra_settings.tpl",
    {
      aws_target_group_arn           = "",
      gcp_backup_account             = "",
      clickhouse_data_size           = module.azure.clickhouse_data_size,
      clickhouse_data_volume_id      = module.azure.clickhouse_data_volume_id,
      clickhouse_gcs_bucket          = "",
      clickhouse_logs_size           = module.azure.clickhouse_logs_size,
      clickhouse_log_volume_id       = module.azure.clickhouse_logs_volume_id,
      clickhouse_s3_bucket           = "",
      clickhouse_s3_region           = "",
      clickhouse_s3_backup_role      = "",
      clickhouse_azblob_client_id    = try(module.azure.service_account_configs[local.clickhouse_backup_sa].azure_identity.client_id, ""),
      clickhouse_azblob_container    = module.azure.azure_blob_container,
      clickhouse_azblob_account_name = module.azure.azure_blob_account_name,
      clickhouse_azblob_account_key  = try(module.azure.service_account_configs[local.clickhouse_backup_sa].azure_identity.client_secret, ""),
      clickhouse_backup_sa           = local.clickhouse_backup_sa,
      cloud_provider                 = module.azure.cloud_provider,
      cluster_name                   = module.azure.cluster_name,
      gcp_neg_name                   = "",
      load_balancer_ips              = [module.azure.load_balancer_ips],
      load_balancer_controller_arn   = "",
      cluster_scaler_role_arn        = "",
      postgres_database              = module.azure.postgres_database_name,
      postgres_password              = module.azure.postgres_password,
      postgres_port                  = local.postgres_port,
      postgres_server                = module.azure.postgres_host,
      postgres_user                  = module.azure.postgres_username,
      redis_data_size                = local.redis_data_size,
      redis_data_volume_id           = module.azure.redis_data_volume_id,
      server_name                    = module.azure.domain_name,
      vpc_cidr                       = module.azure.vpc_cidr,

      # service accounts vars
      dfshell_role_arn                        = try(module.azure.dfshell_role_arn, ""),
      dfshell_service_account_name            = try(module.azure.dfshell_service_account_name, "datafold-dfshell"),
      worker_portal_role_arn                  = try(module.azure.worker_portal_role_arn, ""),
      worker_portal_service_account_name      = try(module.azure.worker_portal_service_account_name, "datafold-worker-portal"),
      operator_role_arn                       = try(module.azure.operator_role_arn, ""),
      operator_service_account_name           = try(module.azure.operator_service_account_name, "datafold-operator"),
      server_role_arn                         = try(module.azure.server_role_arn, ""),
      server_service_account_name             = try(module.azure.server_service_account_name, "datafold-server"),
      scheduler_role_arn                      = try(module.azure.scheduler_role_arn, ""),
      scheduler_service_account_name          = try(module.azure.scheduler_service_account_name, "datafold-scheduler"),
      worker_role_arn                         = try(module.azure.worker_role_arn, ""),
      worker_service_account_name             = try(module.azure.worker_service_account_name, "datafold-worker"),
      worker_catalog_role_arn                 = try(module.azure.worker_catalog_role_arn, ""),
      worker_catalog_service_account_name     = try(module.azure.worker_catalog_service_account_name, "datafold-worker-catalog"),
      worker_interactive_role_arn             = try(module.azure.worker_interactive_role_arn, ""),
      worker_interactive_service_account_name = try(module.azure.worker_interactive_service_account_name, "datafold-worker-interactive"),
      worker_singletons_role_arn              = try(module.azure.worker_singletons_role_arn, ""),
      worker_singletons_service_account_name  = try(module.azure.worker_singletons_service_account_name, "datafold-worker-singletons"),
      worker_lineage_role_arn                 = try(module.azure.worker_lineage_role_arn, ""),
      worker_lineage_service_account_name     = try(module.azure.worker_lineage_service_account_name, "datafold-worker-lineage"),
      worker_monitor_role_arn                 = try(module.azure.worker_monitor_role_arn, ""),
      worker_monitor_service_account_name     = try(module.azure.worker_monitor_service_account_name, "datafold-worker-monitor"),
      storage_worker_role_arn                 = try(module.azure.storage_worker_role_arn, ""),
      storage_worker_service_account_name     = try(module.azure.storage_worker_service_account_name, "datafold-storage-worker"),
      dma_role_arn                            = try(module.azure.dma_role_arn, ""),
      dma_service_account_name                = try(module.azure.dma_service_account_name, "datafold-dma"),
    }
  )
  sensitive = false
}
