# Per-deployment token used by the Datafold server to authorize its
# /livez and /readyz health-check probes. Generated by default and
# overridable via the status_check_token variable.
resource "random_password" "status_check" {
  length  = 48
  special = false
}

locals {
  status_check_token = var.status_check_token != "" ? var.status_check_token : random_password.status_check.result
}
