global:
  datadog:
    env: prod
    install: true
  operator:
    allowRollback: true
    releaseChannel: stable
    backupCronSchedule: 0 1 * * *
    maintenanceWindow: ""
postgres:
  install: false
nginx:
  ingress:
    deploy: true
