global:
  cloudProvider: "azure"
  datadog:
    env: test
    install: true
  operator:
    allowRollback: true
    releaseChannel: foo
    backupCronSchedule: 0 1 * * *
    maintenanceWindow: ""
postgres:
  install: false
nginx:
  ingress:
    deploy: true
datadog:
  configuration:
    apm: false
    monitorPostgres: true
    npm:
      enabled: true
      dnsstats: true
config:
  portalCertData: '-----BEGIN CERTIFICATE-----\nMIIF0DCCBLigAwIBAgIQAVQqsCg8OcOVGz9sD29ewTANBgkqhkiG9w0BAQsFADA8\nMQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRwwGgYDVQQDExNBbWF6b24g\nUlNBIDIwNDggTTAzMB4XDTI0MTIxNjAwMDAwMFoXDTI2MDExNDIzNTk1OVowHTEb\nMBkGA1UEAxMScG9ydGFsLmRhdGFmb2xkLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOC\nAQ8AMIIBCgKCAQEA49uvagYKuBZsXEmq+aPpBwWyw/j8Ke/oO/b1RPqtWjNuZfpd\n4MrjpT9oi1Aq9J29HCN2i7PSZHznaovCm362fEDWqLdfPoVMxicF1Q5qRDe7vvWo\nNZcA0PJckD7RRWB9yInGMxH8IoxbkJ+7qUdOGIreIs6u5c3EVa04wLTjrdiJSAQv\n5UG/qMRkw4YVcx82E6rDwiaft+iONLQwDhs2oPGF/HtteJ57e6Krpy2AymRuq1Oh\nJFPe5Ng2UIEN2ny7kb4uB4SC/Ia9EKvZllXJFKeJwRPWIKwofRCCbzUNHCyWka/J\nhr8Y/W8Q2RzE/spORH97X2uZ4D+3dMg/tH/r9wIDAQABo4IC6zCCAucwHwYDVR0j\nBBgwFoAUVdkYX9IczAHhWLS+q9lVQgHXLgIwHQYDVR0OBBYEFN8sZRehNoz13gJY\nP/kvtJobCGttMB0GA1UdEQQWMBSCEnBvcnRhbC5kYXRhZm9sZC5pbzATBgNVHSAE\nDDAKMAgGBmeBDAECATAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH\nAwEGCCsGAQUFBwMCMDsGA1UdHwQ0MDIwMKAuoCyGKmh0dHA6Ly9jcmwucjJtMDMu\nYW1hem9udHJ1c3QuY29tL3IybTAzLmNybDB1BggrBgEFBQcBAQRpMGcwLQYIKwYB\nBQUHMAGGIWh0dHA6Ly9vY3NwLnIybTAzLmFtYXpvbnRydXN0LmNvbTA2BggrBgEF\nBQcwAoYqaHR0cDovL2NydC5yMm0wMy5hbWF6b250cnVzdC5jb20vcjJtMDMuY2Vy\nMAwGA1UdEwEB/wQCMAAwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB1AA5XlLzz\nrqk+MxssmQez95Dfm8I9cTIl3SGpJaxhxU4hAAABk8+aBkEAAAQDAEYwRAIgJ6Wz\nfFRMIaaKc9GLH1v/BP3JNosLoJtUj5qu7zOLThwCIEwR38uEvcFFix91UnTLs4U1\nUhYLn4SVligtuT9TDsCHAHcAZBHEbKQS7KeJHKICLgC8q08oB9QeNSer6v7VA8l9\nzfAAAAGTz5oGcQAABAMASDBGAiEAs/RTBqGcneECjfiUp4pjEixPo1QnmIMMK86c\n1PwD308CIQDXwFzCQEn+iTpJpSNOP1cXt88oxpuHSXaBIy3YVHXtDAB2AEmcm2ne\nHXzs/DbezYdkprhbrwqHgBnRVVL76esp3fjDAAABk8+aBogAAAQDAEcwRQIgb7vI\nAmTCYkx1kmafnndESNO+YkvPNKzrSpxXhJebVL4CIQCgNffwKFEODQSerrN0h7pf\nwNdL4U66YT4FBCu9OCT43DANBgkqhkiG9w0BAQsFAAOCAQEAHpWxAKJRIoNodVeb\ndhJ3pX3cESS4AjjJaKUR94pJPi0KRoJAFsveR+0fOicCyBsn30hfNl+07P7VEUU0\nP4KZquITE0WmTGoQvFPcrTrqMV5MX8uh0oS6UaBFlZmSBWvO4pX3+D5xJI3RWxrl\nICM49BwHFSWIy51zeiFtiohQ8t8IcQhPCScM+UYqoIOp7DxcLetNY6DDi6nU4UO6\nfy3DakMrCY3XFYuI2LFDGphoyif1HHzmtVysR+E6YBRadoeLikRgg3VNGM2il0GO\n0WO36x7DxrfnPeSRmIprJXXQD8f3ePLMcUzrdyVDdTgyDqKQ8F2UK70v61EdyVHP\nOqkgMw==\n-----END CERTIFICATE-----\n'
worker:
  resources:
    limits:
      memory: 8000Mi
    requests:
      memory: 8000Mi
worker-catalog:
  resources:
    limits:
      memory: 19000Mi
    requests:
      memory: 19000Mi
worker-monitor:
  install: true
  replicaCount: 1
  worker:
    queues: "alerts"
    count: 10
    memory: "2000000"
  resources:
    limits:
      memory: 6Gi
    requests:
      memory: 6Gi
worker-portal:
  install: true
storage-worker:
  install: true
  replicaCount: 1
  worker:
    tasks_ack_late: "true"
  terminationGracePeriodSeconds: "18000"
  resources:
    limits:
      memory: 5Gi
    requests:
      memory: 5Gi
  storage:
    dataSize: 100Gi
